# oas_repo_url: 
# oas_file_path: "oas/petstore.yaml" 
plugin_file_path: 
  - plugin/keyauth.yaml
  - plugin/ratelimmiting.yaml
  - plugin/correlation.yaml
  - plugin/ip-restriction.yaml
global_file_path:
  - global-plugin/request-size-limiting.yaml
