oas_repo:
  url: "https://github.com/krishana2507/petstore-api.git"
  branch: "main"
  file_path: "petstore-api/petstore.yaml"
plugin_file_path: 
  - plugin/keyauth.yaml
  - plugin/ratelimmiting.yaml
  - plugin/correlation.yaml
  - plugin/ip-restriction.yaml
global_file_path:
  - global-plugin/request-size-limiting.yaml
