name: Lint OpenAPI Spec    
  


on:

  push:

    branches:

      - main




jobs:
 
  OAS_TO_Kong:

    runs-on: ubuntu-latest




    steps:

    - name: Checkout Code

      uses: actions/checkout@v2

      # print




    - name: Install Insomnia CLI

      run: |

        wget https://github.com/Kong/insomnia/releases/download/lib%403.12.0/inso-linux-3.12.0.tar.xz

        tar -xf inso-linux-3.12.0.tar.xz



    - name: Lint OpenAPI Spec

      run: ./inso lint spec petstore.yaml

    - name: Generate kong.yaml

      run: ./inso generate config petstore.yaml --type declarative -o kong.yaml

#     - name: open kong.yaml

#       run: cat /home/runner/work/ApiOps/ApiOps/kong.yaml

    - name: install deck CLI

      run: |

        curl -sL https://github.com/kong/deck/releases/download/v1.17.2/deck_1.17.2_linux_amd64.tar.gz -o deck.tar.gz

        tar -xf deck.tar.gz -C /tmp 

        sudo cp /tmp/deck /usr/local/bin/

    - name: update

      run: deck convert --from kong-gateway-2.x --to kong-gateway-3.x --input-file kong.yaml --output-file new-kong.yaml
    - name: download jq
      run: |
       sudo apt install jq -y
         jq --version
        
    - name: download yq
      run: |
          sudo snap install yq
          yq --version
    - name: API Versioning
      run: |
          export w="/default"
          export v="/v1.1"
          cat new-kong.yaml | yq '.services.[].routes.[].paths.[] = env(w)+env(v) + .services.[].routes.[].paths.[]' -o yaml > new-api.yaml
          # deck sync -s new-api.yaml --kong-addr http://13.233.109.117:8001
    - name: plugin implementation
      run: |
          sed -i '1d' MockingPlugin.yaml
          cat MockingPlugin.yaml | yq '.services.[] = env(plugin) + .services.[]' -o yaml > mockplugin.yaml
          cat mockplugin.yaml
    
    - name: check
      run: deck sync -s new-api.yaml --kong-addr http://35.154.219.40:8001

      
    # - name: Commit files
    #   id: commit
    #   run: |
    #       git config --local user.email "krishna.sharma@neosalpha.com"
    #       git config --local user.name "krishna2507"
    #       git add \*.yaml
    #       if [-z "$(git status --porcelain)"]; then
    #          echo "::set-output name=push::false"
    #       else
    #          git commit -m "Add changes sd" -a
    #          echo "::set-output name=push::true"
    #       fi
    #   shell: bash
       
    # - name: Push changes
    #   if: steps.commit.outputs.push == 'true'
    #   uses: ad-m/github-push-action@master
    #   with:
    #        github_token: ${{ secrets.GITHUB_TOKEN }}
  publish-customer-api-to-portal:  # Publish the API to the dev portal
  
    name: Publish OAS to dev portal

    needs: OAS_TO_Kong   # Make sure the completed before running this job

    runs-on: ubuntu-latest  # Use Ubuntu as the operating system for the job

    steps:

      - name: Checkout branch  # Checkout the branch from the repository

        uses: actions/checkout@v2

      - name: Install NodeJs  # Install Node.js for running the dev portal CLI

        uses: actions/setup-node@v3

      - name: Install kon-dev-portal-cli  # Install dev portal CLI

        run: npm install -g kong-portal-cli

      - name: Deploy to dev portal

        run: |          
          sudo cp petstore.yaml workspaces/default/specs
          portal deploy -D default --preserve 

        env:

          KONG_ADMIN_URL: http://35.154.219.40:8001
          

           
           
           
    
#      - name: deck dump
#        run: deck dump -o api-versioning.yaml --kong-addr http://13.233.109.117:8001
       
#      - name: decl sync
#        run: deck sync -s kong-spec1.yaml --kong-addr http://13.233.109.117:8001
   
   
#      - name: download jq
#        run: |
#         sudo apt install jq -y
#         jq --version
        
#      - name: download yq
#        run: |
#          sudo snap install yq
#          yq --version
#      - name: API Versioning
#        run: |
#          export w="/default"
#          export v="/v1.1"
#          cat kong-spec1.yaml | yq '.services.[].routes.[].paths.[] = env(w)+env(v) + .services.[].routes.[].paths.[]' -o yaml > new-api.yaml
#          deck sync -s new-api.yaml --kong-addr http://13.233.109.117:8001
#          git add new-api.yaml
#          git commit -m "push cmoomit"
#          git push

   
        
   
         
    
         

     
