# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    Inso_Download:
     runs-on: ubuntu-latest
     steps:
     - name: Checkout Code
       uses: actions/checkout@v3

      # This will install inso
     - name: Install Insomnia CLI
       run: |
          wget https://github.com/Kong/insomnia/releases/download/lib%403.12.0/inso-linux-3.12.0.tar.xz
          tar -xf inso-linux-3.12.0.tar.xz
          
     - name: Lint OpenAPI Spec
       run: ./inso lint spec insomnia.yaml
       
     - name: Generate kong.yaml
       run: ./inso generate config insomnia.yaml --type declarative -o kong.yaml
    
      # This will insatll deck  
     - name: Install Deck
       run: |
        curl -sL https://github.com/kong/deck/releases/download/v1.17.2/deck_1.17.2_linux_amd64.tar.gz -o deck.tar.gz
        tar -xf deck.tar.gz -C /tmp 
        sudo cp /tmp/deck /usr/local/bin/
        
     - name: update
       run: deck convert --from kong-gateway-2.x --to kong-gateway-3.x --input-file kong.yaml --output-file kong1.yaml
       
     - name: deck ping
       run: deck ping --kong-addr http://13.127.240.238:8001
    
     - name: deck dump
       run: deck dump -o test.yaml --kong-addr http://13.127.240.238:8001
   
     - name: Commit files
       id: commit
       run: |
          git config --local user.email "krishna.sharma@neosalpha.com"
          git config --local user.name "krishna2507"
          git add \*.yaml
          if [-z "$(git status --porcelain)"]; then
             echo "::set-output name=push::false"
          else
             git commit -m "Add changes" -a
             echo "::set-output name=push::true"
          fi
       shell: bash
       
     - name: Push changes
       if: steps.commit.outputs.push == 'true'
       uses: ad-m/github-push-action@master
       with:
           github_token: ${{ secrets.GITHUB_TOKEN }}

   
        
     - name: download jq
       run: |
        sudo apt install jq -y
        jq --version
        
     - name: download yq
       run: |
         sudo apt install yq -y
         yq --version
     - name: API Versioning
       run: |
         export w="/default"
         export v="/v1.1"
         echo $w
         echo $v
         cat test.yaml | yq '.services.[].routes.[].paths.[] = env(w)+env(v) + .services.[].routes.[].paths.[]' -o yaml > api.yaml
          
       
      
         

     
